language: cpp
dist: bionic
addons:
  apt:
     update: true
     packages:
       - libfl-dev
       - libcrypto++-dev 
       - libjsoncpp-dev 
       - libdb5.3-dev 
       - libdb5.3++ 
       - libdb5.3++-dev  

cache:
  apt: true

#install:
#  - travis_retry bash ./admin/travis/verify_build.sh travis_install
    
script: 
  - bash ./admin/travis/verify_build.sh travis_script


